version: '3.8'

services:
# chat
  db_chat:
    container_name: db_chat
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_CHAT_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_CHAT_DATABASE}
      MYSQL_USER: ${DB_CHAT_USER}
      MYSQL_PASSWORD: ${DB_CHAT_PASSWORD}
    ports:
      - ${DB_CHAT_PORT}:3306
    volumes:
      - ./mysql_chat:/var/lib/mysql

  php_chat:
    container_name: php_chat
    build:
      context: ./php
    ports:
      - ${PHP_CHAT_PORT}:9000
    volumes:
      - ./app_chat:/var/www/symfony_docker
    depends_on:
      - db_chat
    environment:
      TOKEN_ACCESS: ${TOKEN_ACCESS}

  nginx_chat:
    container_name: nginx_chat
    image: nginx:stable-alpine
    ports:
      - '${NGINX_CHAT_PORT}:80'
    volumes:
      - ./app_chat:/var/www/symfony_docker
      - ./nginx_chat/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_chat
      - db_chat
